"""Quant-Vis Trading Dashboard — Generated by the quant-vis skill."""

import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Local modules
from data.loader import load_yfinance
from charts.candlestick import create_candlestick, add_trade_markers
from charts.equity_curve import create_equity_curve
from charts.drawdown import create_drawdown_chart, compute_drawdown
from charts.trade_markers import generate_sample_trades
from indicators.fvg import detect as detect_fvg, get_shapes as fvg_shapes
from indicators.structure import detect as detect_structure, get_shapes as structure_shapes
from stats.performance import compute_stats, compute_equity_series

# ─── Page Config ─────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Quant-Vis Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Dark Theme CSS ──────────────────────────────────────────────────────────

st.markdown("""
<style>
    .stApp { background-color: #0e1117; }
    .stat-card {
        background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
        border: 1px solid #2a2a4a;
        border-radius: 10px;
        padding: 15px;
        text-align: center;
        margin: 5px 0;
    }
    .stat-value {
        font-size: 1.8em;
        font-weight: 700;
        color: #00ff88;
        margin: 0;
    }
    .stat-label {
        font-size: 0.8em;
        color: #888;
        margin: 0;
        text-transform: uppercase;
        letter-spacing: 1px;
    }
    .stat-negative .stat-value { color: #ff4444; }
</style>
""", unsafe_allow_html=True)

# ─── Sidebar ─────────────────────────────────────────────────────────────────

st.sidebar.title("📈 Quant-Vis")
st.sidebar.markdown("---")

ticker = st.sidebar.text_input("Ticker", value="SPY")
col1, col2 = st.sidebar.columns(2)
start_date = col1.date_input("Start", value=datetime.now() - timedelta(days=365))
end_date = col2.date_input("End", value=datetime.now())

timeframe = st.sidebar.selectbox("Timeframe", ["1d", "1h", "5m", "15m", "30m", "1wk"], index=0)

st.sidebar.markdown("---")
st.sidebar.subheader("Indicators")
show_fvg = st.sidebar.checkbox("Fair Value Gaps (FVG)", value=True)
fvg_min_gap = st.sidebar.slider("FVG Min Gap %", 0.0, 2.0, 0.0, 0.1) if show_fvg else 0.0
show_structure = st.sidebar.checkbox("Market Structure (BOS/CHoCH)", value=True)
pivot_len = st.sidebar.slider("Pivot Length", 3, 20, 5) if show_structure else 5

st.sidebar.markdown("---")
show_demo_trades = st.sidebar.checkbox("Show Demo Trades", value=True)

# ─── Data Loading ────────────────────────────────────────────────────────────

@st.cache_data(ttl=300)
def fetch_data(t, s, e, tf):
    return load_yfinance(t, start=str(s), end=str(e), interval=tf)

df = fetch_data(ticker, start_date, end_date, timeframe)

if df.empty:
    st.error(f"No data found for {ticker}. Check the ticker and date range.")
    st.stop()

# ─── Indicator Processing ────────────────────────────────────────────────────

shapes = []
annotations = []

if show_fvg:
    df = detect_fvg(df, min_gap_pct=fvg_min_gap / 100)
    shapes.extend(fvg_shapes(df, lookback=len(df)))

if show_structure:
    df = detect_structure(df, pivot_left=pivot_len, pivot_right=pivot_len)
    annotations.extend(structure_shapes(df))

# ─── Main Title ──────────────────────────────────────────────────────────────

st.markdown(f"## {ticker} — {timeframe.upper()} Dashboard")

# ─── Candlestick Chart ───────────────────────────────────────────────────────

fig = create_candlestick(df, title=f"{ticker} Price Action", shapes=shapes, annotations=annotations)

# Demo trade markers
trades_df = pd.DataFrame()
if show_demo_trades and len(df) > 20:
    trades_df = generate_sample_trades(df, n_trades=8)
    fig = add_trade_markers(fig, trades_df)

st.plotly_chart(fig, use_container_width=True)

# ─── Performance Stats ───────────────────────────────────────────────────────

st.markdown("### 📊 Performance")

# Generate demo stats from the sample trades
if show_demo_trades and not trades_df.empty:
    demo_trades = []
    rows = trades_df.to_dict("records")
    for i in range(0, len(rows) - 1, 2):
        entry = rows[i]
        exit_ = rows[i + 1]
        demo_trades.append({
            "entry_price": entry["price"],
            "exit_price": exit_["price"],
            "direction": "long" if entry["side"] == "buy" else "short",
            "entry_date": entry["date"],
            "exit_date": exit_["date"],
        })

    stats = compute_stats(demo_trades)
    equity = compute_equity_series(demo_trades)

    # Stats cards row
    stat_cols = st.columns(len(stats))
    for col, (label, value) in zip(stat_cols, stats.items()):
        neg_class = " stat-negative" if label == "Max Drawdown" else ""
        col.markdown(f"""
        <div class="stat-card{neg_class}">
            <p class="stat-label">{label}</p>
            <p class="stat-value">{value}</p>
        </div>
        """, unsafe_allow_html=True)

    # Equity & Drawdown charts side by side
    eq_col, dd_col = st.columns(2)
    with eq_col:
        eq_fig = create_equity_curve(equity, title="Equity Curve")
        st.plotly_chart(eq_fig, use_container_width=True)
    with dd_col:
        dd_fig = create_drawdown_chart(equity, title="Drawdown")
        st.plotly_chart(dd_fig, use_container_width=True)

    # Trade log
    st.markdown("### 📋 Trade Log")
    log_df = pd.DataFrame(demo_trades)
    log_df["P&L"] = log_df.apply(
        lambda r: (r["exit_price"] - r["entry_price"]) if r["direction"] == "long"
        else (r["entry_price"] - r["exit_price"]), axis=1
    )
    st.dataframe(log_df, use_container_width=True)
else:
    st.info("Enable 'Show Demo Trades' in the sidebar or plug in your strategy's trade list to see performance stats.")

# ─── Footer ──────────────────────────────────────────────────────────────────

st.markdown("---")
st.markdown(
    "<p style='text-align:center; color:#555; font-size:0.8em;'>"
    "Generated by <b>Quant-Vis</b> • Powered by OpenClaw"
    "</p>",
    unsafe_allow_html=True,
)
